name: Continuous Delivery
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - my-branch # ou qualquer outra branch
jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: |
            atp.py

